In [1]:
import os

In [2]:
os.getcwd()

'C:\\Users\\P SRIJAY'

In [3]:
os.chdir("C:/Users/P SRIJAY/Desktop")

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
data1=pd.read_csv("imo.csv")

In [6]:
data1

Loan ID  Cla  Wb  Ycj  Tp  Act  Pd  Le
0         1    4  23    8   1    1   1   1
1         2    6  18    1   1    2   0   0
2         3    8  24    8   2    2   0   1
3         4    3  25    3   3    3   0   0
4         5    2  20    5   1    4   0   1
5         6    8  17   10   4    1   0   1
6         7    2  18    1   1    7   1   0
7         8    6  18    1   3    3   0   0
8         9    5  19    2   2    7   0   1
9        10    2  23    1   1    1   0   1
10       11    9  25    3   4    2   0   1
11       12    5  18   10   1    1   0   1
12       13    9  24    1   5    6   0   0
13       14    8  20    4   3    5   1   0
14       15    2  23   10   1    2   1   1
15       16    4  18    9   3    4   0   1
16       17    6  18    7   3    3   0   0
17       18    6  23   10   3    7   0   1
18       19    7  18   10   1    2   1   1
19       20    4  24    8   1    3   0   1
20       21    3  17    8   3    1   0   0
21       22    1  25    1   1    6   0   1
22       23    2  21    2   1    2   0   0
23       24    9  22   10   1    3   0   1
24       25    2  20    4   3    4   0   0
25       26    4  16    3   3    5   0   0
26       27    7  22    1   4    2   0   1
27       28    4  24    2   2    7   0   0
28       29    9  24   10   5    1   0   1
29       30    7  18    0   1    6   0   0
30       31    1  27    6   1    2   1   1
31       32    3  22    2   2    4   0   1
32       33    4  23    1   2    1   1   1
33       34    3  22   10   3    7   0   1
34       36    6  18   10   3    5   0   0
35       37    5  24    5   2    3   0   1
36       38    9  24    4   1    2   1   1
37       40    1  22    8   1    1   1   1
38       41    2  23    8   1    5   0   0
39       42    4  21    8   2    1   0   1
40       43    6  19    1   4    3   0   0
41       44    2  18    2   1    5   0   1
42       45    3  18    4   3    1   0   0
43       46    2  21   10   1    2   0   1
44       47    3  19    4   3    3   0   0
45       48    2  25    1   1    4   0   1
46       49    1  22   10   1    6   0   1
47       50    2  16    1   2    3   0   0
48       51    4  21    8   1    1   0   1

In [7]:
data1.drop(['Loan ID'],axis=1)

Cla  Wb  Ycj  Tp  Act  Pd  Le
0     4  23    8   1    1   1   1
1     6  18    1   1    2   0   0
2     8  24    8   2    2   0   1
3     3  25    3   3    3   0   0
4     2  20    5   1    4   0   1
5     8  17   10   4    1   0   1
6     2  18    1   1    7   1   0
7     6  18    1   3    3   0   0
8     5  19    2   2    7   0   1
9     2  23    1   1    1   0   1
10    9  25    3   4    2   0   1
11    5  18   10   1    1   0   1
12    9  24    1   5    6   0   0
13    8  20    4   3    5   1   0
14    2  23   10   1    2   1   1
15    4  18    9   3    4   0   1
16    6  18    7   3    3   0   0
17    6  23   10   3    7   0   1
18    7  18   10   1    2   1   1
19    4  24    8   1    3   0   1
20    3  17    8   3    1   0   0
21    1  25    1   1    6   0   1
22    2  21    2   1    2   0   0
23    9  22   10   1    3   0   1
24    2  20    4   3    4   0   0
25    4  16    3   3    5   0   0
26    7  22    1   4    2   0   1
27    4  24    2   2    7   0   0
28    9  24   10   5    1   0   1
29    7  18    0   1    6   0   0
30    1  27    6   1    2   1   1
31    3  22    2   2    4   0   1
32    4  23    1   2    1   1   1
33    3  22   10   3    7   0   1
34    6  18   10   3    5   0   0
35    5  24    5   2    3   0   1
36    9  24    4   1    2   1   1
37    1  22    8   1    1   1   1
38    2  23    8   1    5   0   0
39    4  21    8   2    1   0   1
40    6  19    1   4    3   0   0
41    2  18    2   1    5   0   1
42    3  18    4   3    1   0   0
43    2  21   10   1    2   0   1
44    3  19    4   3    3   0   0
45    2  25    1   1    4   0   1
46    1  22   10   1    6   0   1
47    2  16    1   2    3   0   0
48    4  21    8   1    1   0   1

In [8]:
data1.Le.value_counts()

1    30
0    19
Name: Le, dtype: int64

In [9]:
x=data1.iloc[:,1:7]

In [10]:
x

Cla  Wb  Ycj  Tp  Act  Pd
0     4  23    8   1    1   1
1     6  18    1   1    2   0
2     8  24    8   2    2   0
3     3  25    3   3    3   0
4     2  20    5   1    4   0
5     8  17   10   4    1   0
6     2  18    1   1    7   1
7     6  18    1   3    3   0
8     5  19    2   2    7   0
9     2  23    1   1    1   0
10    9  25    3   4    2   0
11    5  18   10   1    1   0
12    9  24    1   5    6   0
13    8  20    4   3    5   1
14    2  23   10   1    2   1
15    4  18    9   3    4   0
16    6  18    7   3    3   0
17    6  23   10   3    7   0
18    7  18   10   1    2   1
19    4  24    8   1    3   0
20    3  17    8   3    1   0
21    1  25    1   1    6   0
22    2  21    2   1    2   0
23    9  22   10   1    3   0
24    2  20    4   3    4   0
25    4  16    3   3    5   0
26    7  22    1   4    2   0
27    4  24    2   2    7   0
28    9  24   10   5    1   0
29    7  18    0   1    6   0
30    1  27    6   1    2   1
31    3  22    2   2    4   0
32    4  23    1   2    1   1
33    3  22   10   3    7   0
34    6  18   10   3    5   0
35    5  24    5   2    3   0
36    9  24    4   1    2   1
37    1  22    8   1    1   1
38    2  23    8   1    5   0
39    4  21    8   2    1   0
40    6  19    1   4    3   0
41    2  18    2   1    5   0
42    3  18    4   3    1   0
43    2  21   10   1    2   0
44    3  19    4   3    3   0
45    2  25    1   1    4   0
46    1  22   10   1    6   0
47    2  16    1   2    3   0
48    4  21    8   1    1   0

In [11]:
y=data1.iloc[:,7]

In [12]:
y

0     1
1     0
2     1
3     0
4     1
5     1
6     0
7     0
8     1
9     1
10    1
11    1
12    0
13    0
14    1
15    1
16    0
17    1
18    1
19    1
20    0
21    1
22    0
23    1
24    0
25    0
26    1
27    0
28    1
29    0
30    1
31    1
32    1
33    1
34    0
35    1
36    1
37    1
38    0
39    1
40    0
41    1
42    0
43    1
44    0
45    1
46    1
47    0
48    1
Name: Le, dtype: int64

In [13]:
from sklearn import *

In [14]:
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))

In [15]:
minmax.fit(x).transform(x)

C:\Users\P SRIJAY\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


array([[0.375     , 0.63636364, 0.8       , 0.        , 0.        ,
        1.        ],
       [0.625     , 0.18181818, 0.1       , 0.        , 0.16666667,
        0.        ],
       [0.875     , 0.72727273, 0.8       , 0.25      , 0.16666667,
        0.        ],
       [0.25      , 0.81818182, 0.3       , 0.5       , 0.33333333,
        0.        ],
       [0.125     , 0.36363636, 0.5       , 0.        , 0.5       ,
        0.        ],
       [0.875     , 0.09090909, 1.        , 0.75      , 0.        ,
        0.        ],
       [0.125     , 0.18181818, 0.1       , 0.        , 1.        ,
        1.        ],
       [0.625     , 0.18181818, 0.1       , 0.5       , 0.33333333,
        0.        ],
       [0.5       , 0.27272727, 0.2       , 0.25      , 1.        ,
        0.        ],
       [0.125     , 0.63636364, 0.1       , 0.        , 0.        ,
        0.        ],
       [1.        , 0.81818182, 0.3       , 0.75      , 0.16666667,
        0.        ],
       [0.5       , 0

In [16]:
x.describe()

Cla         Wb        Ycj         Tp        Act         Pd
count  49.000000  49.000000  49.000000  49.000000  49.000000  49.000000
mean    4.428571  21.020408   5.224490   2.102041   3.306122   0.183673
std     2.516611   2.846707   3.618617   1.194517   1.991692   0.391230
min     1.000000  16.000000   0.000000   1.000000   1.000000   0.000000
25%     2.000000  18.000000   2.000000   1.000000   2.000000   0.000000
50%     4.000000  21.000000   4.000000   2.000000   3.000000   0.000000
75%     6.000000  23.000000   8.000000   3.000000   5.000000   0.000000
max     9.000000  27.000000  10.000000   5.000000   7.000000   1.000000

In [17]:
data1.corr()

Loan ID       Cla        Wb       Ycj        Tp       Act        Pd  \
Loan ID  1.000000 -0.316140  0.004124  0.032232 -0.110224 -0.002976 -0.113509   
Cla     -0.316140  1.000000 -0.018695  0.073860  0.497990 -0.093223 -0.039297   
Wb       0.004124 -0.018695  1.000000  0.019770 -0.104778 -0.023172  0.164919   
Ycj      0.032232  0.073860  0.019770  1.000000 -0.048788 -0.214969  0.073279   
Tp      -0.110224  0.497990 -0.104778 -0.048788  1.000000  0.030381 -0.308416   
Act     -0.002976 -0.093223 -0.023172 -0.214969  0.030381  1.000000 -0.180608   
Pd      -0.113509 -0.039297  0.164919  0.073279 -0.308416 -0.180608  1.000000   
Le       0.015438  0.002402  0.436881  0.400730 -0.285594 -0.237631  0.161151   

               Le  
Loan ID  0.015438  
Cla      0.002402  
Wb       0.436881  
Ycj      0.400730  
Tp      -0.285594  
Act     -0.237631  
Pd       0.161151  
Le       1.000000

In [69]:
from sklearn import model_selection,neighbors

In [70]:
from sklearn.model_selection import train_test_split

In [71]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [72]:
X_train

Cla  Wb  Ycj  Tp  Act  Pd
0     4  23    8   1    1   1
34    6  18   10   3    5   0
35    5  24    5   2    3   0
32    4  23    1   2    1   1
1     6  18    1   1    2   0
38    2  23    8   1    5   0
42    3  18    4   3    1   0
17    6  23   10   3    7   0
39    4  21    8   2    1   0
45    2  25    1   1    4   0
48    4  21    8   1    1   0
4     2  20    5   1    4   0
44    3  19    4   3    3   0
41    2  18    2   1    5   0
11    5  18   10   1    1   0
43    2  21   10   1    2   0
46    1  22   10   1    6   0
18    7  18   10   1    2   1
20    3  17    8   3    1   0
24    2  20    4   3    4   0
6     2  18    1   1    7   1
15    4  18    9   3    4   0
19    4  24    8   1    3   0
12    9  24    1   5    6   0
16    6  18    7   3    3   0
22    2  21    2   1    2   0
25    4  16    3   3    5   0
10    9  25    3   4    2   0
28    9  24   10   5    1   0
21    1  25    1   1    6   0
26    7  22    1   4    2   0
3     3  25    3   3    3   0
9     2  23    1   1    1   0
2     8  24    8   2    2   0

In [73]:
y_train=y_train.astype('int')

In [74]:
y_test=y_test.astype('int')

In [75]:
clf=neighbors.KNeighborsClassifier()

In [76]:
clf.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [77]:
y_predict=clf.predict(X_test)

In [78]:
y_train_predict=clf.predict(X_train)

In [79]:
accuracy=clf.score(X_train,y_train)

In [80]:
accuracy

0.7941176470588235

In [30]:
accuracy_score(y_test,y_pred)*100

NameError: name 'accuracy_score' is not defined

In [81]:
from sklearn.linear_model import LogisticRegression

In [82]:
lr=LogisticRegression()

In [83]:
lr.fit(X_train,y_train)

C:\Users\P SRIJAY\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [84]:
from sklearn.model_selection import cross_val_score,cross_val_predict

In [85]:
lr_acc=cross_val_score(lr,X_train,y_train,cv=3,scoring='accuracy',n_jobs=-1)

In [86]:
lr_acc

array([0.75      , 0.72727273, 0.63636364])

In [87]:
y_pred=lr.predict(X_test)

In [88]:
y_test.values

array([1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1])

In [89]:
y_pred

array([1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1])

In [90]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix

In [91]:
accuracy_score(y_test,y_pred)*100

73.33333333333333

In [92]:
confusion_matrix(y_test,y_pred)

array([[4, 2],
       [2, 7]], dtype=int64)

In [93]:
from sklearn.svm import SVC

In [94]:
svc=SVC(kernel='rbf',probability=True)

In [95]:
svc_classifier=svc.fit(X_train,y_train)

C:\Users\P SRIJAY\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [96]:
svc_acc=cross_val_score(svc_classifier,X_train,y_train,cv=3,scoring='accuracy',n_jobs=1)

C:\Users\P SRIJAY\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\P SRIJAY\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\P SRIJAY\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [97]:
svc_acc

array([0.58333333, 0.36363636, 0.63636364])

In [98]:
y_test_pred=svc_classifier.predict(X_test)

In [99]:
accuracy_score(y_test,y_test_pred)*100

66.66666666666666

In [100]:
from sklearn.tree import DecisionTreeClassifier

In [101]:
dtc_clf=DecisionTreeClassifier()

In [102]:
dtc_clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [103]:
dtc_clf_acc=cross_val_score(dtc_clf,X_train,y_train,cv=3,scoring='accuracy',n_jobs=-1)

In [104]:
dtc_clf_probs=cross_val_predict(dtc_clf,X_train,y_train,cv=3,method='predict_proba')

In [105]:
dtc_clf_acc

array([0.58333333, 0.27272727, 0.63636364])

In [106]:
y_pred=dtc_clf.predict(X_test)

In [107]:
accuracy_score(y_test,y_pred)*100

80.0

In [108]:
from sklearn.ensemble import RandomForestClassifier

In [109]:
rmf=RandomForestClassifier(max_depth=3,random_state=0)

In [110]:
rmf.fit(X_train,y_train)

C:\Users\P SRIJAY\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=3, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [111]:
rmf_acc=cross_val_score(rmf,X_train,y_train,cv=3,scoring='accuracy',n_jobs=-1)

In [112]:
rmf_proba=cross_val_predict(rmf,X_train,y_train,cv=3,method='predict_proba')

In [113]:
y_pred=rmf.predict(X_test)

In [114]:
y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1])

In [115]:
y_test.values

array([1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1])

In [116]:
accuracy_score(y_test,y_pred)*100

86.66666666666667

In [117]:
confusion_matrix(y_test,y_pred)

array([[5, 1],
       [1, 8]], dtype=int64)

In [68]:
import pickle
from sklearn.externals import joblib
filename='imo.pkl'
joblib.dump(clf,filename)

['imo.pkl']

In [694]:
import pickle
from sklearn.externals import joblib
filename='imo1.pkl'
joblib.dump(lr,filename)

['imo1.pkl']